### ISSUE TITLE
README를 작성해주세요

### ISSUE THREAD

**Issue by hannut91** [CodeSoom/project-spring-1-developerOlive#24]
README에 프로젝트 소개를 간략하게 작성하고, 어떻게 사용해볼 수 있는지 문서를 작성해주시면 좋을 것 같습니다

**Comment by developerOlive** [comment]
넵 정리하여 작성하겠습니다!

**Comment by developerOlive** [comment]
2021년 4월 10일 README 초안 작성하였습니다 :)
추후 업데이트 예정입니다!
