### ISSUE TITLE
로그인이 꼭 필요한 앱인가요?

### ISSUE THREAD

**Issue by hannut91** [CodeSoom/project-spring-1-developerOlive#33]
익명의 사람이 들어와서 타로만 보고 싶다면, 볼 수 있을까요?

**Comment by developerOlive** [comment]
1. 익명의 사람이 들어와서 자유롭게 타로만 볼 수 있습니다.
2. 본인이 본 타로 내용을 저장하고 싶을 때만 로그인 기능이 필요합니다.

**Comment by hannut91** [comment]
와 ㅎㅎ 좋네요! 그렇지만 타로 내용을 저장하기 위해서만 로그인 기능을 사용하기에는 너무 큰 기능일 것 같아요. 
왜 본인이 본 타로 내용을 저장해야 하나요? 목적이 무엇이에요? 공유가 목적인가요? 아니면 그냥 히스토리 관리인가요?

**Comment by developerOlive** [comment]
사실 코드숨 과정에서 배웠던 jwt 토큰, security, 패스워드 암호화를 
프로젝트 하면서 다시 한 번 복습하고 싶어서 로그인 기능을 넣은 이유도 있긴 해요...😂

일단 본인이 본 타로 내용을 저장하는 이유는 다음과 같습니다!

1. '오늘의 운세' 타로를 보았습니다.
2. 왠지 이거.. 재미로 봤는데 잘 들어 맞는거 같아요. 
3. 근데 이 프로그램 창을 끄면 날아가기 때문에 캡쳐를 해야 할 것 같아요.
4. 캡쳐를 해도 되지만 저장 기능이 있어도 좋을 것 같아요.

저장 기능의 목적은 내가 봤던 타로 내용을 다시 한 번 보고 싶을 때를 위함이라고 할 수 있겠어요!!
