### ISSUE TITLE
SNS에 공유를 할 수 있으면 좋을 것 같아요.

### ISSUE THREAD

**Issue by hannut91** [CodeSoom/project-spring-1-developerOlive#47]
결과를 바로 페이스북이나 카톡으로도 공유하기 기능이 있으면 좋을 것 같습니다

**Comment by developerOlive** [comment]
저도 이 기능이 있었으면 좋겠다고 생각했는데, 
4주 내 완성이라서 일단 우선순위 기능은 아니고 advanced 기능으로 남겨두었어요 ㅎㅎ ㅠㅠ
현재 구현하고 있는 기능이 시간 내 잘 끝난다면 도전해보면 좋을 것 같아요.
